apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: webapp
  labels:
    app: employees
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: application
        image: 645071556982.dkr.ecr.us-east-1.amazonaws.com/application:v0.2
        env:
          - name: DBPWD
            value: mysql
          - name: DBUSER
            value: root
          - name: DBHOST
            value: "mysql.database.svc.cluster.local"
          - name: DBPORT
            value: "3306"
        ports:
        - containerPort: 8080