apiVersion: v1
kind: Pod
metadata:
  name: application
  namespace: webapp
spec:
  containers:
    - name: application
      image: 645071556982.dkr.ecr.us-east-1.amazonaws.com/application:v0.1
      env:
        - name: DBPWD
          value: mysql
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080