apiVersion: v1
kind: Service
metadata:
  name: applicationv2
  namespace: application
  labels:
    app: employees
    version: v2
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
    app: employees
    version: v2