apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 645071556982.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        ports:
        - containerPort: 3306