apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: database
spec:
  containers:
    - name: mysql
      image: 645071556982.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.2
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
      ports:
        - containerPort: 3306