apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: database
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 645071556982.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: mysql
        ports:
          - containerPort: 3306